language: objective-c
osx_image: xcode8.3

before_install:
- pod repo update

script:
- pod repo update
- xcodebuild build -workspace PhotoCollectionView.xcworkspace -scheme PhotoCollectionView -sdk iphonesimulator
- xcodebuild build -workspace PhotoCollectionView.xcworkspace -scheme PhotoCollectionViewDemo -sdk iphonesimulator
- xcodebuild build -workspace PhotoCollectionView.xcworkspace -scheme PhotoCollectionView -sdk iphoneos
